feat: add docs about auctions and protocol tokens
blend-capital/blend-docs pull request #4
Opened 2024-10-31 18:54 UTC by mootz12

2024-10-31 20:19 UTC, markuspluna requested changes
Few small changes needed

2024-10-31 20:19 UTC, markuspluna commented on tech-docs/core-contracts/lending-pool/protocol-tokens.md
> +# Protocol Tokens
We should call out these are purely accounting structures. Calling this Protocol Accounting may be a better option

2024-10-31 20:19 UTC, markuspluna commented on tech-docs/core-contracts/lending-pool/protocol-tokens.md
> +# Protocol Tokens
Yeah I think just use the word token less, tokenized should be cut entirely

2024-10-31 20:19 UTC, markuspluna commented on users/auctions.md
> +The bid contains only the backstop token. On a successful fill, the backstop token is transferred from the bidder to the pool.
Add link that explains what a backstop token is (or a description)

2024-10-31 20:32 UTC, Ryang-21 commented on pool-creators/selecting-an-oracle.md
> +It is required to verify that "lastprice" works for all potential reserves the pool will maintain. Please note that the Blend pool will always invoke the oracle with `Stellar::Asset({contract_id})` t
is it worth noting that `contract_id` is an `Address` object?

2024-10-31 22:01 UTC, drew-boy commented on pool-creators/selecting-an-oracle.md
> +It is required to verify that "lastprice" works for all potential reserves the pool will maintain. Please note that the Blend pool will always invoke the oracle with `Stellar::Asset({contract_id})` t
take out 'that' in 'please note that...'

2024-10-31 22:03 UTC, drew-boy commented on pool-creators/selecting-an-oracle.md
>  When a generalized oracle is insufficient for a pool, i.e. it doesn't support all assets the pool needs prices for, the pool creator may need to use an oracle adaptor. An oracle adaptor is a custom o
", i.e. it doesn't support all assets the pool needs prices for," -> (i.e. it doesn't support all assets the pool needs prices for)

2024-11-05 19:56 UTC, markuspluna approved these changes

2024-11-05 21:47 UTC, merged